name: analyse

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  phpstan:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.4

    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-8.1

    - name: Install dependencies
      if: steps.cache-descom-laravel-auth.outputs.cache-hit != 'true'
      run: |
        composer install
        composer dump

    - name: Run analyse phpstan
      run: vendor/bin/phpstan analyse --error-format github